### ISSUE TITLE
Missing the data files

### ISSUE THREAD

**Issue by DylanHaiyangChen** [rutviksharedalal95/Supply_Chain_Back_Order#1]
I find a problem: 
In the NN_GridSearch.py, there is 
features_df = pd.read_csv("DataRUS.csv").

The file ''DataRUS.csv'' is not included in the repository. Do you mean the file ''CleanedData.csv'' which is already in the file directory?

**Comment by rutviksharedalal95** [comment]
Sorry about that. I have added it now.

**Comment by DylanHaiyangChen** [comment]
Great. It is completed now.
